// Scene 11: The Great Hydration Debate. Dialogue drives the bubbles, mouths and voices; music is synthesized from the score below.
asset({
  title: 'The Great Hydration Debate',
  logline: 'After winning their game, Housam and Alma race to the cooler, but Professor Safadi says sports drinks are just sugar. They win the debate with eight reasons, and he lets them drink... his Safadi Energy Drinks: unsweetened tea.',
  files: ['scene.js'],
  docs: 'README.md',
  cast: ['housam', 'alma', 'safadi'],
  locations: ['soccer_field'],
  dialogue: [
    // Scene 1: the final whistle, the race to the cooler
    { at: 3.4, speaker: 'housam', text: 'We... did it...', cps: 11, hold: .5, energy: .8 },
    { at: 5.6, speaker: 'alma', text: "Last-minute goal... I can't feel my legs.", cps: 19, hold: .5 },
    { at: 8.6, speaker: 'housam', text: 'Need... drink...', cps: 10, hold: .4, energy: .8 },
    { at: 14.4, speaker: 'alma', text: 'Race you!', cps: 12, hold: .4, kind: 'shout', energy: 1.3 },
    { at: 18.9, speaker: 'housam', text: 'Oh yeah... *hydration drinks*.', cps: 17, hold: .4 },
    // Scene 2: the challenge
    { at: 21.9, speaker: 'safadi', text: 'Ah ah ah! *Energy drinks*? After a game?', cps: 19, hold: .5, energy: 1.1 },
    { at: 25.0, speaker: 'housam', text: "Professor! They're not energy drinks...", cps: 19, hold: .2 },
    { at: 27.7, speaker: 'housam', text: "They're *hydration* drinks!", cps: 17, hold: .4, energy: 1.1 },
    { at: 30.1, speaker: 'alma', text: 'Totally different category.', cps: 18, hold: .5 },
    { at: 32.6, speaker: 'safadi', text: 'Colorful sugar water in a bottle.', cps: 19, hold: .3 },
    { at: 35.1, speaker: 'safadi', text: "Kids shouldn't be drinking that stuff.", cps: 19, hold: .5 },
    { at: 38.6, speaker: 'housam', text: 'Professor... I have *eight* reasons.', cps: 18, hold: .5 },
    { at: 41.5, speaker: 'safadi', text: 'Eight. Go on, then.', cps: 16, hold: .5 },
    // 1 · electrolytes
    { at: 46.6, speaker: 'housam', text: 'Reason one: *electrolytes*!', cps: 18, hold: .3, energy: 1.1 },
    { at: 48.8, speaker: 'safadi', text: 'Do you even know what electrolytes *are*?', cps: 19, hold: .3 },
    { at: 51.9, speaker: 'housam', text: '"They help regulate *blood pressure*, *blood sugar* and *heart rate*!"', cps: 20, hold: .4 },
    { at: 56.0, speaker: 'alma', text: 'Your *HEART RATE*, Professor!', cps: 17, hold: .5, kind: 'shout', energy: 1.2 },
    { at: 58.6, speaker: 'safadi', text: "Fine. I'll give you that one.", cps: 18, hold: .5 },
    // 2 · instant energy
    { at: 61.2, speaker: 'safadi', text: 'But *water* hydrates you just as well.', cps: 19, hold: .3 },
    { at: 63.9, speaker: 'alma', text: "True. It's not *better* than water...", cps: 18, hold: .2 },
    { at: 66.5, speaker: 'safadi', text: 'So you *agree* with me!', cps: 18, hold: .4, energy: 1.1 },
    { at: 68.5, speaker: 'alma', text: 'BUT! Sports drinks give you energy *fast*!', cps: 19, hold: .3, kind: 'shout', energy: 1.2 },
    { at: 71.4, speaker: 'alma', text: 'Your team is down two goals? One sip...', cps: 19, hold: .2 },
    { at: 78.6, speaker: 'alma', text: "...and you're off scoring goals!", cps: 18, hold: .5 },
    // 3 · sugar
    { at: 81.3, speaker: 'safadi', text: 'And the *sugar*? An *ocean* of sugar!', cps: 19, hold: .5 },
    { at: 84.1, speaker: 'housam', text: 'Partially right, Professor. *Partially*.', cps: 18, hold: .4 },
    { at: 87.1, speaker: 'alma', text: 'They make *low-sugar* flavors now.', cps: 18, hold: .2 },
    { at: 89.6, speaker: 'housam', text: 'And *ZERO* sugar! ZERO!', cps: 15, hold: .4, kind: 'shout', energy: 1.25 },
    { at: 91.9, speaker: 'alma', text: 'Small bottles for little kids... big ones for the pros!', cps: 20, hold: .4 },
    // 4 + 6 · tournaments and endurance
    { at: 97.2, speaker: 'housam', text: 'One game, fine. But a *tournament*?', cps: 18, hold: .3 },
    { at: 99.8, speaker: 'alma', text: 'And *carbs* for long games. Ninety minutes!', cps: 19, hold: .4 },
    // 5 · sweat
    { at: 104.9, speaker: 'alma', text: 'When you sweat, you lose *electrolytes*.', cps: 19, hold: .2 },
    { at: 107.6, speaker: 'housam', text: 'Sports drinks put them *back*!', cps: 18, hold: .3 },
    { at: 110.9, speaker: 'safadi', text: '...Noted.', cps: 10, hold: .6, energy: .85 },
    // 7 · kids actually drink
    { at: 112.9, speaker: 'alma', text: 'Tasty drinks make kids *drink more*!', cps: 19, hold: .3 },
    { at: 115.45, speaker: 'housam', text: 'From five years old to fifteen!', cps: 19, hold: .3 },
    // 8 · a meal without the meal
    { at: 117.8, speaker: 'safadi', text: 'A real *meal* is healthier.', cps: 18, hold: .5 },
    { at: 120.2, speaker: 'housam', text: "Big meal before a game? You'll *throw up*!", cps: 19, hold: .2 },
    { at: 125.0, speaker: 'alma', text: 'Drinks give you energy without the *heavy stuff*.', cps: 20, hold: .4 },
    // the sponsor break
    { at: 128.4, speaker: 'housam', text: 'This debate is brought to you by *3-DOLPHINS*...', cps: 19, hold: .1, energy: 1.15 },
    { at: 131.3, speaker: 'housam', text: '...the best 3-D printing company in the world!', cps: 20, hold: .3, energy: 1.15 },
    { at: 134.3, speaker: 'alma', text: 'Housam!', cps: 12, hold: .3, kind: 'shout', energy: 1.2 },
    { at: 135.6, speaker: 'housam', text: "What? They're sponsoring us!", cps: 18, hold: .5 },
    // closing statement
    { at: 138.1, speaker: 'alma', text: 'In conclusion: energy, electrolytes, zero sugar...', cps: 20, hold: .1 },
    { at: 141.0, speaker: 'alma', text: '...and kids actually drink it!', cps: 19, hold: .3 },
    { at: 143.3, speaker: 'housam', text: 'The defense *rests*.', cps: 16, hold: .6 },
    // Scene 3: the verdict, the toast, the taste
    { at: 148.6, speaker: 'safadi', text: 'Well... that was very *convincing*.', cps: 16, hold: .3 },
    { at: 151.4, speaker: 'alma', text: 'Really?!', cps: 12, hold: .4, kind: 'shout', energy: 1.25 },
    { at: 151.4, speaker: 'housam', text: 'Really?!', cps: 12, hold: .4, energy: 1.1, silentBubble: true },
    { at: 152.9, speaker: 'safadi', text: "Go ahead. You've *earned* it.", cps: 18, hold: .4 },
    { at: 159.2, speaker: 'housam', text: 'To *victory*!', cps: 15, hold: .3, energy: 1.2 },
    { at: 160.6, speaker: 'alma', text: 'To *electrolytes*!', cps: 16, hold: .3, energy: 1.2 },
    { at: 165.0, speaker: 'housam', text: '...Mmf?', cps: 10, hold: .4, energy: .8 },
    { at: 166.5, speaker: 'alma', text: 'Why does it taste like... *leaves*?', cps: 17, hold: .4 },
    { at: 169.2, speaker: 'housam', text: 'Bitter leaves. *Sad* leaves.', cps: 16, hold: .5, energy: .85 },
    { at: 176.0, speaker: 'safadi', text: 'You said it yourselves. *Zero sugar*.', cps: 18, hold: .3 },
    { at: 178.7, speaker: 'alma', text: 'You *swapped* them?!', cps: 15, hold: .4, kind: 'shout', energy: 1.25 },
    { at: 180.8, speaker: 'safadi', text: 'Safadi Energy Drinks... for the whole team!', cps: 19, hold: .3 },
    { at: 183.7, speaker: 'safadi', text: 'Very healthy. Heh heh heh...', cps: 12, hold: .4, energy: .9 },
    { at: 186.8, speaker: 'housam', text: "This isn't what we argued for!", cps: 18, hold: .4, energy: 1.1 },
    { at: 189.3, speaker: 'safadi', text: 'Drink up. *Electrolytes*, remember?', cps: 18, hold: .6 },
    // Scene 4: the long walk away (voice only)
    { at: 194.0, speaker: 'safadi', text: 'Heh heh heh...', cps: 9, hold: .2, energy: .8, silentBubble: true },
  ],
  music: {
    prompt: 'A bright, bouncy park-soccer underscore that turns into a playful courtroom-quiz groove for the debate: plucky bass, bells and a light pulse. A referee whistle opens it; it thins under every argument, adds a small ding as each point lands, a cheesy jingle for the sponsor break, a ticking clock while Safadi thinks, a triumphant lift for the toast, then drops out on the sour gulp and ends on a small, smug chuckle. Instrumental under dialogue.',
    bpm: 112, tonic: 62, motif: [0, 2, 4, 7, 4, 2, 4, 5], chords: [0, 4, 5, 3],
    sections: [
      { at: 0, energy: .55 }, { at: 3.2, energy: .25 }, { at: 11.0, energy: .3 }, { at: 14.4, energy: .7 }, { at: 18.2, energy: .35 },
      { at: 21.4, energy: 0 }, { at: 22.4, energy: .25 }, { at: 43.6, energy: .8 }, { at: 46.4, energy: .28 },
      { at: 73.9, energy: .75 }, { at: 78.4, energy: .28 }, { at: 122.8, energy: .45 }, { at: 124.9, energy: .28 },
      { at: 128.3, energy: .6 }, { at: 134.3, energy: .28 }, { at: 144.6, energy: 0 }, { at: 148.5, energy: .25 },
      { at: 151.4, energy: .6 }, { at: 159.0, energy: .75 }, { at: 162.4, energy: 0 }, { at: 171.8, energy: .15 },
      { at: 176.0, energy: .25 }, { at: 192.2, energy: .2 }, { at: 198.4, energy: 0 },
    ],
    cues: [
      { at: .7, type: 'whistle' }, { at: 11.8, type: 'bonk' }, { at: 15.2, type: 'whoosh' }, { at: 18.4, type: 'pop' }, { at: 18.7, type: 'ding' },
      { at: 21.4, type: 'bonk' }, { at: 38.0, type: 'pop' }, { at: 42.6, type: 'bonk' }, { at: 43.7, type: 'bonk' }, { at: 44.1, type: 'ding' },
      { at: 51.3, type: 'plip' }, { at: 57.0, type: 'bonk' }, { at: 57.5, type: 'bonk' }, { at: 60.2, type: 'ding' },
      { at: 74.3, type: 'whoosh' }, { at: 76.6, type: 'whoosh' }, { at: 77.0, type: 'ding' },
      { at: 81.6, type: 'plip' }, { at: 86.5, type: 'ding' }, { at: 90.0, type: 'pop' }, { at: 92.8, type: 'pop' }, { at: 93.8, type: 'pop' },
      { at: 96.1, type: 'plip' }, { at: 102.7, type: 'whoosh' }, { at: 103.1, type: 'ding' },
      { at: 108.6, type: 'plip' }, { at: 109.0, type: 'plip' }, { at: 109.7, type: 'bonk' }, { at: 117.4, type: 'ding' },
      { at: 118.1, type: 'plip' }, { at: 123.3, type: 'bonk' }, { at: 124.3, type: 'bonk' },
      { at: 128.4, type: 'pop' }, { at: 128.7, type: 'pop' }, { at: 129.0, type: 'ding' }, { at: 134.9, type: 'whoosh' },
      { at: 144.6, type: 'pop' }, { at: 145.6, type: 'plip' }, { at: 146.4, type: 'plip' }, { at: 147.2, type: 'plip' }, { at: 148.0, type: 'plip' },
      { at: 153.4, type: 'ding' }, { at: 156.0, type: 'pop' }, { at: 157.5, type: 'plip' }, { at: 158.6, type: 'whoosh' },
      { at: 162.2, type: 'ding' }, { at: 162.7, type: 'gulp' }, { at: 163.1, type: 'gulp' }, { at: 164.2, type: 'scratch' },
      { at: 172.8, type: 'whoosh' }, { at: 173.3, type: 'ding' }, { at: 192.6, type: 'gulp' }, { at: 195.4, type: 'gulp' },
    ],
  },
});
