asset({
  title: 'Jenna Teaches Danny Division',
  logline: 'At Meadow Ridge Elementary, Jenna teaches Danny division with toy cars and a whiteboard candy example. Danny solves fourteen divided by two, earns cars and candies, and meets Jenna’s toy giraffe Fafy at the closing wink.',
  files: ['scene.js'],
  docs: 'README.md',
  cast: ['jenna', 'danny'],
  locations: ['meadow-ridge-elementary-school'],
  music: {
    prompt: 'A gentle MIDI-style classroom tune throughout the lesson: bright synthesized bell notes, soft triangle-wave chords and a warm bass pulse. Curious, friendly and calm, a little brighter for Danny’s discoveries and playtime. Keep the accompaniment quiet under dialogue and soften the closing bars for Jenna’s wink with Fafy.',
    bpm: 100, tonic: 60,
    motif: [0, 2, 4, 2, 1, 3, 2, 0], chords: [0, 3, 4, 0],
    sections: [
      { at: 0, energy: .28 }, { at: 45, energy: .20 }, { at: 68, energy: .28 },
      { at: 80, energy: .24 }, { at: 130, energy: .20 }, { at: 150, energy: .30 },
      { at: 172, energy: .24 }, { at: 194, energy: .30 }, { at: 214, energy: .32 },
      { at: 223, energy: .26 }, { at: 231, energy: .12 }, { at: 234, energy: .03 },
    ],
  },
  dialogue: [
    { at: 3, speaker: 'danny', text: 'Hey Jenna, what’s division?', cps: 18, hold: 1.7 },
    { at: 7, speaker: 'jenna', text: 'Division is breaking numbers into *equal groups*.', cps: 18, hold: 1.8 },
    { at: 12, speaker: 'danny', text: 'Can you give me an example?', cps: 18, hold: 1.8 },
    { at: 16, speaker: 'jenna', text: 'For example, if Mom brings us *four toy cars*…', cps: 18, hold: 2.8 },
    { at: 22, speaker: 'jenna', text: '…and we want to have the same amount, we need to divide four into *two equal parts*.', cps: 19, hold: 2.1 },
    { at: 29, speaker: 'jenna', text: 'Do we both have the same number? How many cars does *each person* get?', cps: 20, hold: 1.8 },
    { at: 35, speaker: 'danny', text: '*Two!*', cps: 16, hold: 2.8 },
    { at: 39, speaker: 'jenna', text: 'Yes! If you add *two twice*, it equals *four*.', cps: 18, hold: 2.8 },
    { at: 49, speaker: 'jenna', text: 'Hey Danny, concentrate on the lesson!', cps: 18, hold: 2.3 },
    { at: 54, speaker: 'danny', text: 'I want to play with the cars! And I want *more!*', cps: 17, hold: 3.6 },
    { at: 61, speaker: 'jenna', text: 'We’ll play when we’re done. First, how many cars did *each of us* get?', cps: 19, hold: 2.7 },
    { at: 68, speaker: 'danny', text: '*Two!* And *two plus two* makes *four!*', cps: 17, hold: 3.3 },
    { at: 74, speaker: 'jenna', text: 'Exactly! That’s *division*.', cps: 18, hold: 2.2 },
    { at: 80, speaker: 'jenna', text: 'Let’s try another example using numbers on my *whiteboard*!', cps: 19, hold: 2.7 },
    { at: 87, speaker: 'danny', text: 'Whoa! Those numbers are *huge*! That looks way too hard!', cps: 18, hold: 3.5 },
    { at: 95, speaker: 'jenna', text: 'Don’t worry, here’s a secret trick: division is just *subtraction over and over again*!', cps: 19, hold: 3.2 },
    { at: 104, speaker: 'jenna', text: 'Imagine you have *45 pieces of candy*.', cps: 18, hold: 2.8 },
    { at: 110, speaker: 'jenna', text: 'Every time a friend comes over, you hand them *9 pieces*.', cps: 18, hold: 3.1 },
    { at: 118, speaker: 'jenna', text: 'You keep subtracting *9 pieces* from your pile until you have *zero* left.', cps: 19, hold: 3.0 },
    { at: 126, speaker: 'jenna', text: 'Count how many friends got candy.', cps: 18, hold: 2.1 },
    { at: 150, speaker: 'danny', text: 'Look, Jenna! You subtracted nine *five times*! So forty-five divided by nine is *five*!', cps: 21, hold: 3.4 },
    { at: 160, speaker: 'jenna', text: 'Great job, Danny! You *nailed it*!', cps: 19, hold: 2.6 },
    { at: 166, speaker: 'danny', text: 'Mmm, candy! Can I eat some right now?', cps: 19, hold: 2.7 },
    { at: 172, speaker: 'jenna', text: 'Focus, silly! We get treats *after the lesson*.', cps: 19, hold: 2.7 },
    { at: 178, speaker: 'danny', text: 'Oh, I get it now! So division is either sharing things into *equal groups*…', cps: 20, hold: 2.7 },
    { at: 186, speaker: 'danny', text: '…or subtracting the *same amount* over and over!', cps: 20, hold: 3.0 },
    { at: 194, speaker: 'danny', text: 'I get it now! *14 divided by 2 is 7!*', cps: 18, hold: 3.7 },
    { at: 202, speaker: 'jenna', text: '*Good job*, Danny!', cps: 18, hold: 2.3 },
    { at: 207, speaker: 'jenna', text: 'Lesson finished—now you can play and have some *candies*!', cps: 19, hold: 2.6 },
    { at: 214, speaker: 'danny', text: '*Race time!* And treats!', cps: 18, hold: 2.3 },
    { at: 223, speaker: 'jenna', text: 'Next time, we’ll learn *something else new*!', cps: 18, hold: 4.0 },
  ],
});
