// Scene 08: Safadi's multitasking experiment with Jester Fester. Dialogue drives the bubbles, mouths and voices.
asset({
  title: "Even the Juggler Can't Multitask",
  logline: 'In the lecture hall, Professor Safadi has the class count Jester Fester\'s juggling balls while doing mental math. On the second try, "What is 9 × 8?" makes Fester fumble, and the balls bonk them both.',
  files: ['scene.js'],
  docs: 'README.md',
  cast: ['safadi', 'jester_fester', 'housam', 'alma'],
  locations: ['lecture_hall'],
  dialogue: [
    { at: 0.8, speaker: 'safadi', text: 'Your attention is like a *spotlight*.', cps: 20, hold: .8 },
    { at: 4.0, speaker: 'safadi', text: 'It can shine on *one thing* at a time.', cps: 20, hold: .9 },
    { at: 7.3, speaker: 'safadi', text: 'Try to do two things at once...', cps: 20, hold: .4 },
    { at: 9.8, speaker: 'safadi', text: '...and you do *worse at both*.', cps: 18, hold: 1.0 },
    { at: 13.0, speaker: 'safadi', text: "Don't believe me? Let me *prove* it.", cps: 21, hold: .5 },
    { at: 15.7, speaker: 'safadi', text: 'Please welcome... *Jester Fester*!', cps: 18, hold: .8, energy: 1.1 },
    { at: 20.9, speaker: 'jester_fester', text: 'Ta-daaa!', cps: 14, hold: .9, energy: 1.2 },
    { at: 23.4, speaker: 'safadi', text: 'Your job: *count the balls* he juggles...', cps: 21, hold: .5 },
    { at: 26.4, speaker: 'safadi', text: '...and at the same time, solve a *math problem*.', cps: 22, hold: .8 },
    { at: 29.9, speaker: 'safadi', text: 'Ready? Try it with me!', cps: 20, hold: .5 },
    { at: 33.4, speaker: 'safadi', text: 'Count the balls! And... what is *7 × 6*?', cps: 20, hold: 1.4 },
    { at: 42.3, speaker: 'safadi', text: 'Time! How many balls?', cps: 20, hold: .6, energy: 1.1 },
    { at: 44.6, speaker: 'housam', text: 'Uh... six? No, four?', cps: 18, hold: .7 },
    { at: 46.9, speaker: 'alma', text: 'I forgot the *math* part!', cps: 20, hold: .8 },
    { at: 49.4, speaker: 'safadi', text: 'Five balls. And 7 × 6 is *42*.', cps: 19, hold: .9 },
    { at: 52.5, speaker: 'safadi', text: "Tricky, right? Let's try a *second time*.", cps: 21, hold: .7 },
    { at: 55.7, speaker: 'jester_fester', text: 'This time... *seven* balls!', cps: 19, hold: .7, energy: 1.1 },
    { at: 60.0, speaker: 'safadi', text: 'Count the balls!', cps: 18, hold: 1.0 },
    { at: 63.9, speaker: 'safadi', text: 'What is *9 × 8*?', cps: 15, hold: .7 },
    { at: 64.7, speaker: 'jester_fester', text: '9 × 8...?', cps: 10, hold: .7, kind: 'think' },
    { at: 68.6, speaker: 'safadi', text: 'Ow... You see?', cps: 16, hold: .5, energy: .9 },
    { at: 70.7, speaker: 'safadi', text: "Even the *juggler* can't multitask!", cps: 18, hold: 1.4 },
  ],
  music: {
    prompt: 'Light, bouncy lecture-hall comedy underscore: plucky bass and bells. It thins out while the class counts, speeds up for the seven-ball cascade, drops out for the fumble, punctuates each bonk, and ends on a warm little flourish when the last ball lands on the hat. Instrumental under dialogue.',
    bpm: 96, tonic: 62, motif: [0, 2, 4, 5, 4, 2, 4, 7], chords: [0, 3, 4, 0],
    sections: [
      { at: 0, energy: .22 }, { at: 12.8, energy: .3 }, { at: 18.3, energy: .55 }, { at: 23.2, energy: .28 },
      { at: 31.9, energy: .45 }, { at: 33.4, energy: .2 }, { at: 42.2, energy: .25 }, { at: 49.2, energy: .28 },
      { at: 58.2, energy: .62 }, { at: 63.9, energy: .35 }, { at: 65.2, energy: 0 }, { at: 68.2, energy: .12 },
      { at: 74.4, energy: .45 }, { at: 78.9, energy: .55 }, { at: 81.2, energy: .1 },
    ],
    cues: [
      { at: 18.3, type: 'whoosh' }, { at: 20.6, type: 'ding' }, { at: 31.9, type: 'pop' }, { at: 58.2, type: 'pop' },
      { at: 65.25, type: 'whoosh' }, { at: 66.3, type: 'bonk' }, { at: 66.65, type: 'bonk' }, { at: 67.0, type: 'bonk' },
      { at: 78.9, type: 'plip' }, { at: 79.3, type: 'ding' },
    ],
  },
});
