// Scene 10: The Great Debate. Dialogue drives the bubbles, mouths and voices; music is synthesized from the score below.
asset({
  title: 'The Great Debate',
  logline: 'Outside DCES, Professor Safadi says kids should read books, not play video games. Housam takes him on in the lecture hall, the audience votes for Housam, and Safadi gives in: only thirty minutes a day.',
  files: ['scene.js'],
  docs: 'README.md',
  cast: ['safadi', 'housam', 'alma', 'jester_fester', 'dragon'],
  locations: ['dces', 'lecture_hall'],
  dialogue: [
    // DCES: the challenge
    { at: 2.6, speaker: 'safadi', text: 'Children! A question for today...', cps: 19, hold: .5 },
    { at: 5.8, speaker: 'safadi', text: 'Kids should *read books*... not play *video games*!', cps: 19, hold: .9 },
    { at: 10.2, speaker: 'housam', text: 'I *disagree*, Professor.', cps: 17, hold: .7 },
    { at: 12.6, speaker: 'safadi', text: 'Ah! Then we have a *debate*!', cps: 18, hold: .4, energy: 1.1 },
    { at: 14.9, speaker: 'safadi', text: 'To the *lecture hall*!', cps: 17, hold: .5, energy: 1.15 },
    // Lecture hall · round 1: mindless?
    { at: 19.2, speaker: 'safadi', text: 'Video games are *mindless*.', cps: 18, hold: .4 },
    { at: 21.8, speaker: 'safadi', text: 'Left, right, dodge, shoot, repeat!', cps: 19, hold: .6 },
    { at: 25.0, speaker: 'housam', text: 'Not anymore! Take *Breath of the Wild*...', cps: 19, hold: .4 },
    { at: 28.3, speaker: 'housam', text: 'Swords, spears, bows, armor, recipes...', cps: 20, hold: .3 },
    { at: 31.2, speaker: 'housam', text: 'You have to *process* it all!', cps: 18, hold: .6 },
    { at: 34.0, speaker: 'dragon', text: 'Recipes? I like *recipes*.', cps: 16, hold: .7 },
    // round 2: lonely?
    { at: 37.0, speaker: 'safadi', text: 'Reading together builds *friendships*.', cps: 20, hold: .4 },
    { at: 40.0, speaker: 'safadi', text: 'Games *isolate* kids.', cps: 17, hold: .5 },
    { at: 42.4, speaker: 'housam', text: 'Try *Overcooked 2*! One kitchen, two cooks...', cps: 20, hold: .3 },
    { at: 45.6, speaker: 'housam', text: '...you *have* to talk to win!', cps: 18, hold: .5 },
    { at: 48.3, speaker: 'housam', text: 'Teams that gamed for 45 minutes were *20% more productive*!', cps: 21, hold: .8 },
    { at: 52.6, speaker: 'alma', text: 'Like dancing with a *partner*!', cps: 18, hold: .5 },
    { at: 55.0, speaker: 'jester_fester', text: 'Or juggling with a partner!', cps: 19, hold: .4, energy: 1.1 },
    // round 3: dumber?
    { at: 58.8, speaker: 'safadi', text: 'Books make you *think*.', cps: 17, hold: .4 },
    { at: 61.0, speaker: 'safadi', text: 'Games make you... well... *dumber*.', cps: 18, hold: .6 },
    { at: 64.0, speaker: 'housam', text: 'One *Phantom Hourglass* puzzle...', cps: 19, hold: .3 },
    { at: 66.4, speaker: 'housam', text: '...has *58 quadrillion* wrong answers!', cps: 18, hold: .6, energy: 1.1 },
    { at: 69.8, speaker: 'dragon', text: 'Is a quadrillion more than... *eleven*?', cps: 17, hold: .6 },
    { at: 73.0, speaker: 'alma', text: '*Way* more, Dragon.', cps: 16, hold: .6 },
    { at: 75.2, speaker: 'housam', text: 'And 2,000 kids who gamed had better *working memory*.', cps: 21, hold: .7 },
    // Safadi scores a point
    { at: 79.6, speaker: 'safadi', text: 'Aha! A *link* is not a *cause*!', cps: 17, hold: .4, energy: 1.15 },
    { at: 82.4, speaker: 'safadi', text: 'Maybe smart kids just *like* games.', cps: 19, hold: .5 },
    { at: 85.6, speaker: 'housam', text: '...Fair point, Professor.', cps: 17, hold: .4 },
    { at: 88.0, speaker: 'housam', text: 'But games also *lower stress*...', cps: 18, hold: .3 },
    { at: 90.5, speaker: 'housam', text: "...and there's a game for *everybody*!", cps: 19, hold: .6 },
    // the vote
    { at: 94.2, speaker: 'safadi', text: 'Very well! Time to *vote*.', cps: 18, hold: .3 },
    { at: 96.6, speaker: 'safadi', text: 'Which side was more *compelling*?', cps: 19, hold: .4 },
    { at: 99.4, speaker: 'safadi', text: 'Who votes for *books*?', cps: 16, hold: .6 },
    { at: 104.2, speaker: 'safadi', text: '...And for *video games*?', cps: 16, hold: .5 },
    { at: 108.6, speaker: 'safadi', text: 'Hmm... *all* of you?', cps: 14, hold: .7 },
    // the twist
    { at: 111.4, speaker: 'safadi', text: 'Fine. You can play *video games*.', cps: 17, hold: .5 },
    { at: 114.0, speaker: 'alma', text: 'Yaaay!', cps: 12, hold: .6, kind: 'shout', energy: 1.3 },
    { at: 118.2, speaker: 'safadi', text: '...*Thirty minutes* a day.', cps: 14, hold: .8 },
    { at: 121.8, speaker: 'alma', text: 'Awww...', cps: 8, hold: .7, energy: .9 },
    { at: 121.8, speaker: 'housam', text: 'Awww...', cps: 8, hold: .7, energy: .8, silentBubble: true },
    { at: 121.8, speaker: 'jester_fester', text: 'Awww...', cps: 8, hold: .7, energy: .8, silentBubble: true },
    { at: 121.8, speaker: 'dragon', text: 'Awww...', cps: 8, hold: .7, energy: .8, silentBubble: true },
    { at: 124.4, speaker: 'safadi', text: 'Heh heh heh...', cps: 10, hold: 1.0, energy: .9 },
  ],
  music: {
    prompt: 'A light, curious quiz-show underscore: plucky bass, bells and a steady pulse. It thins under the arguments, adds a tick as each chalk line lands, drops to a lone cricket when nobody votes for books, swells when the kids cheer, stops dead on a record scratch at "thirty minutes a day", and ends on a small warm chuckle. Instrumental under dialogue.',
    bpm: 104, tonic: 60, motif: [0, 4, 2, 5, 4, 7, 5, 4], chords: [0, 3, 4, 0],
    sections: [
      { at: 0, energy: .35 }, { at: 16.6, energy: .6 }, { at: 18.4, energy: .28 }, { at: 34, energy: .32 },
      { at: 55.4, energy: .45 }, { at: 58.4, energy: .28 }, { at: 79.4, energy: .4 }, { at: 85.4, energy: .26 },
      { at: 94, energy: .3 }, { at: 101.4, energy: 0 }, { at: 106.2, energy: .5 }, { at: 108.4, energy: .2 },
      { at: 111.2, energy: .25 }, { at: 114, energy: .85 }, { at: 120.9, energy: 0 }, { at: 124.2, energy: .18 }, { at: 127.2, energy: 0 },
    ],
    cues: [
      { at: 5.6, type: 'bonk' }, { at: 17.0, type: 'whoosh' }, { at: 17.3, type: 'ding' },
      { at: 18.5, type: 'plip' }, { at: 18.9, type: 'plip' }, { at: 21.0, type: 'plip' }, { at: 33.0, type: 'plip' },
      { at: 41.4, type: 'plip' }, { at: 51.6, type: 'plip' }, { at: 57.3, type: 'bonk' }, { at: 63.0, type: 'plip' },
      { at: 66.9, type: 'whoosh' }, { at: 75.4, type: 'plip' }, { at: 78.6, type: 'plip' },
      { at: 79.7, type: 'ding' }, { at: 85.8, type: 'plip' }, { at: 90.0, type: 'plip' }, { at: 93.2, type: 'plip' },
      { at: 101.6, type: 'cricket' }, { at: 102.7, type: 'cricket' }, { at: 103.6, type: 'cricket' },
      { at: 106.6, type: 'pop' }, { at: 107.0, type: 'pop' }, { at: 107.4, type: 'pop' },
      { at: 114.0, type: 'ding' }, { at: 119.8, type: 'plip' }, { at: 120.9, type: 'scratch' },
    ],
  },
});
