// Scene 15: The Second Half. Dialogue drives the bubbles, mouths and voices; music is synthesized from the score below.
// A `group` on a line draws one bubble for everyone in it (the other speakers' entries are silentBubble, so they still voice).
asset({
  title: 'The Second Half',
  logline: 'The second half: the kids beat the offside trap by dribbling. Danny scores, Alma scores past an ice-cream daydream, the twins fight back with two penalties and a wonder strike, and Housam wins it 4-3. Then the twins offer the kids the cooler... and keep the real drinks for themselves. The End.',
  files: ['scene.js'],
  docs: 'README.md',
  cast: ['safadi', 'sami', 'housam', 'alma', 'jenna', 'danny', 'jester_fester'],
  locations: ['soccer_field'],
  dialogue: [
    { at: 6.2, speaker: 'safadi', text: "Zero-zero, brother. They can't score if they're always *offside*.", cps: 18, hold: 0.4 },
    { at: 9.8, speaker: 'safadi', text: "Heh heh heh...", cps: 11, hold: 0.5, group: ['safadi', 'sami'], energy: 0.9 },
    { at: 9.8, speaker: 'sami', text: "Heh heh heh...", cps: 11, hold: 0.5, silentBubble: true, energy: 0.9 },
    { at: 14.2, speaker: 'jenna', text: "Every time we pass... *offside*!", cps: 17, hold: 0.4 },
    { at: 16.8, speaker: 'danny', text: "No fair.", cps: 11, hold: 0.5, energy: 0.85 },
    { at: 18.4, speaker: 'housam', text: "Wait. Offside only counts when we *pass* forward.", cps: 18, hold: 0.4 },
    { at: 22.6, speaker: 'alma', text: "So... we don't pass?", cps: 15, hold: 0.4 },
    { at: 24.6, speaker: 'housam', text: "We *DRIBBLE*. Take it past Professor Safadi yourself... then shoot!", cps: 19, hold: 0.5, energy: 1.15 },
    { at: 28.6, speaker: 'housam', text: "TEAM KIDS!", cps: 12, hold: 0.6, kind: 'shout', energy: 1.35, group: ['housam', 'alma', 'jenna', 'danny'] },
    { at: 28.6, speaker: 'alma', text: "TEAM KIDS!", cps: 12, hold: 0.6, silentBubble: true, energy: 1.35 },
    { at: 28.6, speaker: 'jenna', text: "TEAM KIDS!", cps: 12, hold: 0.6, silentBubble: true, energy: 1.35 },
    { at: 28.6, speaker: 'danny', text: "TEAM KIDS!", cps: 12, hold: 0.6, silentBubble: true, energy: 1.35 },
    { at: 35.8, speaker: 'housam', text: "Danny! Remember the *plan*!", cps: 17, hold: 0.3, kind: 'shout', energy: 1.25 },
    { at: 41.0, speaker: 'safadi', text: "Wake up, *BRO*!", cps: 14, hold: 0.4, kind: 'shout', energy: 1.3 },
    { at: 44.0, speaker: 'sami', text: "*OFFSIDE!*", cps: 12, hold: 0.4, kind: 'shout', energy: 1.25 },
    { at: 45.6, speaker: 'housam', text: "NOT!", cps: 10, hold: 0.6, kind: 'shout', energy: 1.4, group: ['housam', 'danny', 'jester_fester'] },
    { at: 45.6, speaker: 'danny', text: "NOT!", cps: 10, hold: 0.6, silentBubble: true, energy: 1.4 },
    { at: 45.6, speaker: 'jester_fester', text: "NOT!", cps: 10, hold: 0.6, silentBubble: true, energy: 1.4 },
    { at: 47.2, speaker: 'jester_fester', text: "He dribbled it himself. *Goal!*", cps: 18, hold: 0.5 },
    { at: 58.0, speaker: 'alma', text: "Oh right... the *plan*!", cps: 16, hold: 0.3 },
    { at: 59.6, speaker: 'safadi', text: "Come back here!", cps: 16, hold: 0.4, energy: 1.15 },
    { at: 66.4, speaker: 'sami', text: "Do you want an... *ice cream*?", cps: 15, hold: 0.5, energy: 0.9 },
    { at: 70.6, speaker: 'housam', text: "Sister, *WAKE UP*!", cps: 15, hold: 0.3, kind: 'shout', energy: 1.35 },
    { at: 73.0, speaker: 'alma', text: "GOAAAL!", cps: 11, hold: 0.6, kind: 'shout', energy: 1.4 },
    { at: 77.0, speaker: 'sami', text: "They're... good.", cps: 13, hold: 0.3, energy: 0.8 },
    { at: 78.6, speaker: 'safadi', text: "*Too* good.", cps: 12, hold: 0.4, energy: 0.8 },
    { at: 85.0, speaker: 'jester_fester', text: "*Penalty!*", cps: 12, hold: 0.5, kind: 'shout', energy: 1.25 },
    { at: 96.4, speaker: 'sami', text: "Did I do *that*?", cps: 14, hold: 0.6 },
    { at: 100.2, speaker: 'danny', text: "Hey!", cps: 10, hold: 0.3, kind: 'shout', energy: 1.2 },
    { at: 104.0, speaker: 'jester_fester', text: "*Yellow card!* Penalty!", cps: 16, hold: 0.5, energy: 1.2 },
    { at: 105.8, speaker: 'alma', text: "Oops...", cps: 10, hold: 0.5, energy: 0.85 },
    { at: 112.0, speaker: 'safadi', text: "Heh heh heh!", cps: 11, hold: 0.4, group: ['safadi', 'sami'], energy: 1.2 },
    { at: 112.0, speaker: 'sami', text: "Heh heh heh!", cps: 11, hold: 0.4, silentBubble: true, energy: 1.2 },
    { at: 123.0, speaker: 'jester_fester', text: "Free kick, Adults!", cps: 16, hold: 0.4 },
    { at: 125.6, speaker: 'sami', text: "Oops.", cps: 10, hold: 0.5, energy: 0.85 },
    { at: 128.8, speaker: 'housam', text: "GOAAAL!", cps: 11, hold: 0.6, kind: 'shout', energy: 1.4 },
    { at: 131.8, speaker: 'jester_fester', text: "*FULL TIME!* The Kids win!", cps: 16, hold: 0.6, kind: 'shout', energy: 1.3 },
    { at: 142.0, speaker: 'safadi', text: "Well played, team. You *earned* it...", cps: 17, hold: 0.3 },
    { at: 145.0, speaker: 'safadi', text: "...go grab an *energy drink* from the cooler.", cps: 18, hold: 0.4 },
    { at: 148.4, speaker: 'alma', text: "Stop! He swapped them with *unsweetened tea*!", cps: 18, hold: 0.3, kind: 'shout', energy: 1.25 },
    { at: 151.8, speaker: 'alma', text: "Don't fall for this *trap*!", cps: 16, hold: 0.4, energy: 1.1 },
    { at: 154.0, speaker: 'housam', text: "Ohhh.", cps: 10, hold: 0.3, group: ['housam', 'alma', 'jenna', 'danny'] },
    { at: 154.0, speaker: 'alma', text: "Ohhh.", cps: 10, hold: 0.3, silentBubble: true },
    { at: 154.0, speaker: 'jenna', text: "Ohhh.", cps: 10, hold: 0.3, silentBubble: true },
    { at: 154.0, speaker: 'danny', text: "Ohhh.", cps: 10, hold: 0.3, silentBubble: true },
    { at: 163.4, speaker: 'sami', text: "Unsweet *tea*?", cps: 13, hold: 0.6 },
    { at: 168.6, speaker: 'safadi', text: "*Not* this time, brother.", cps: 15, hold: 0.5 },
    { at: 172.4, speaker: 'safadi', text: "Heh heh heh...", cps: 11, hold: 0.6, group: ['safadi', 'sami'], energy: 0.9 },
    { at: 172.4, speaker: 'sami', text: "Heh heh heh...", cps: 11, hold: 0.6, silentBubble: true, energy: 0.9 },
  ],
  music: {
    prompt: 'The match score from scene 14, now brighter: a smug half-time noodle for the twins, a "plan" theme that builds as Housam figures it out, a driving pulse for play that stops on every whistle, a dreamy harp for the ice-cream daydream, big brassy stings for each goal, a cheeky twin "heh heh heh" motif for the comeback, a triumphant full-time swell, and a sly little tag on the label reveal before THE END.',
    bpm: 120, tonic: 62, motif: [0, 2, 4, 7, 9, 7, 4, 2], chords: [0, 4, 5, 3],
    sections: [
      { at: 0, energy: .3 }, { at: 12, energy: .25 }, { at: 18.4, energy: .5 }, { at: 28.6, energy: .8 }, { at: 31.0, energy: .6 }, { at: 38, energy: .85 },
      { at: 43.4, energy: 1 }, { at: 44.0, energy: .3 }, { at: 49.0, energy: .7 }, { at: 58.8, energy: .8 }, { at: 66.2, energy: .3 }, { at: 68.6, energy: .4 },
      { at: 71.6, energy: .9 }, { at: 76, energy: .2 }, { at: 80, energy: .7 }, { at: 86.4, energy: .35 }, { at: 89.0, energy: .7 }, { at: 99.2, energy: .7 },
      { at: 104, energy: .3 }, { at: 109, energy: .75 }, { at: 114, energy: .8 }, { at: 120.3, energy: 1 }, { at: 122.6, energy: .5 }, { at: 126, energy: .9 },
      { at: 131.2, energy: 1 }, { at: 142, energy: .3 }, { at: 160, energy: .25 }, { at: 166.5, energy: .6 }, { at: 175, energy: .8 }, { at: 179.4, energy: 0 },
    ],
    cues: [
      { at: 31.0, type: 'whistle' }, 
      { at: 43.6, type: 'whistle' }, 
      { at: 84.6, type: 'whistle' }, 
      { at: 89.2, type: 'whistle' }, 
      { at: 95.8, type: 'whistle' }, 
      { at: 103.6, type: 'whistle' }, 
      { at: 109.2, type: 'whistle' }, 
      { at: 120.5, type: 'whistle' }, 
      { at: 123.0, type: 'whistle' }, 
      { at: 128.4, type: 'whistle' }, 
      { at: 131.2, type: 'whistle' }, 
      { at: 43.4, type: 'ding' }, 
      { at: 72.8, type: 'ding' }, 
      { at: 89.0, type: 'ding' }, 
      { at: 95.7, type: 'ding' }, 
      { at: 109.0, type: 'ding' }, 
      { at: 120.3, type: 'ding' }, 
      { at: 128.2, type: 'ding' }, 
      { at: 34.0, type: 'whoosh' }, 
      { at: 38.1, type: 'whoosh' }, 
      { at: 42.8, type: 'bonk' }, 
      { at: 44.0, type: 'plip' }, 
      { at: 53.4, type: 'bonk' }, 
      { at: 57.7, type: 'pop' }, 
      { at: 68.6, type: 'plip' }, 
      { at: 71.6, type: 'pop' }, 
      { at: 72.2, type: 'bonk' }, 
      { at: 84.3, type: 'bonk' }, 
      { at: 88.6, type: 'bonk' }, 
      { at: 92.6, type: 'bonk' }, 
      { at: 93.8, type: 'plip' }, 
      { at: 94.7, type: 'plip' }, 
      { at: 95.3, type: 'plip' }, 
      { at: 103.3, type: 'bonk' }, 
      { at: 108.6, type: 'bonk' }, 
      { at: 112.0, type: 'bonk' }, 
      { at: 119.8, type: 'whoosh' }, 
      { at: 124.6, type: 'bonk' }, 
      { at: 127.8, type: 'bonk' }, 
      { at: 160.6, type: 'pop' }, 
      { at: 166.5, type: 'ding' }, 
      { at: 171.0, type: 'ding' }, 
      { at: 171.6, type: 'gulp' }, 
      { at: 177.2, type: 'ding' },
    ],
  },
});
