// Scene 14: The Offside Trap. Dialogue drives the bubbles, mouths and voices; music is synthesized from the score below.
// A `group` on a line draws one bubble for everyone in it (the other speakers' entries are silentBubble, so they still voice).
asset({
  title: 'The Offside Trap',
  logline: 'The first half: the Safadi twins spring the offside trap. Danny scores, offside. Alma saves, Housam scores with a backflip bicycle kick, offside again. "WHY???" Referee Fester explains offside Safadi-style until Safadi cuts him off. Half-time, 0-0. To be continued...',
  files: ['scene.js'],
  docs: 'README.md',
  cast: ['safadi', 'sami', 'housam', 'alma', 'jenna', 'danny', 'jester_fester'],
  locations: ['soccer_field'],
  dialogue: [
    // the huddle and kick-off
    { at: 4.6, speaker: 'safadi', text: 'Brother... you guard the goal. I stay up front.', cps: 17, hold: .4, energy: .8 },
    { at: 8.2, speaker: 'sami', text: "And I'll guard it... very... *relaxingly*.", cps: 15, hold: .5, energy: .85 },
    { at: 11.8, speaker: 'safadi', text: 'Heh heh heh...', cps: 11, hold: .5, energy: .9, group: ['safadi', 'sami'] },
    { at: 11.8, speaker: 'sami', text: 'Heh heh heh...', cps: 11, hold: .5, energy: .9, silentBubble: true },
    { at: 14.3, speaker: 'alma', text: 'Ready, Team Kids?', cps: 16, hold: .4, kind: 'shout', energy: 1.2 },
    { at: 16.0, speaker: 'housam', text: 'READY!', cps: 12, hold: .5, kind: 'shout', energy: 1.3, group: ['housam', 'danny', 'jenna'] },
    { at: 16.0, speaker: 'danny', text: 'READY!', cps: 12, hold: .5, energy: 1.3, silentBubble: true },
    { at: 16.0, speaker: 'jenna', text: 'READY!', cps: 12, hold: .5, energy: 1.3, silentBubble: true },
    // goal 1
    { at: 20.6, speaker: 'safadi', text: 'Ah-ha! *Mine!*', cps: 14, hold: .4, energy: 1.1 },
    { at: 27.8, speaker: 'danny', text: 'GOAAAL!', cps: 11, hold: .7, kind: 'shout', energy: 1.4, group: ['danny', 'housam', 'jenna'] },
    { at: 27.8, speaker: 'housam', text: 'GOAAAL!', cps: 11, hold: .7, energy: 1.4, silentBubble: true },
    { at: 27.8, speaker: 'jenna', text: 'GOAAAL!', cps: 11, hold: .7, energy: 1.4, silentBubble: true },
    { at: 29.5, speaker: 'alma', text: 'Woo-hoo!', cps: 12, hold: .4, energy: 1.3 },
    { at: 31.9, speaker: 'jester_fester', text: "No, no, no! That doesn't count.", cps: 17, hold: .3 },
    { at: 34.4, speaker: 'jester_fester', text: '*OFFSIDE!*', cps: 12, hold: .6, kind: 'shout', energy: 1.3 },
    { at: 36.2, speaker: 'sami', text: 'Huh? Did we *win*?', cps: 15, hold: .5 },
    { at: 38.4, speaker: 'safadi', text: 'Heh heh heh...', cps: 11, hold: .2, energy: .9 },
    { at: 39.6, speaker: 'sami', text: 'Heh heh heh...', cps: 11, hold: .2, energy: .9 },
    // the charge and the save
    { at: 44.0, speaker: 'jenna', text: 'Stop right there!', cps: 17, hold: .3, energy: 1.2 },
    { at: 45.6, speaker: 'safadi', text: 'Professor Safadi... *SHOOTS!*', cps: 17, hold: .3, energy: 1.2 },
    { at: 49.0, speaker: 'safadi', text: 'WHAAAT?!', cps: 10, hold: .6, kind: 'shout', energy: 1.35 },
    { at: 51.0, speaker: 'alma', text: 'Not in *my* goal.', cps: 15, hold: .7 },
    // goal 2
    { at: 56.6, speaker: 'danny', text: 'Housam!', cps: 12, hold: .3, kind: 'shout', energy: 1.2 },
    { at: 60.4, speaker: 'housam', text: 'GOAAAL!', cps: 11, hold: .7, kind: 'shout', energy: 1.4, group: ['housam', 'danny', 'jenna'] },
    { at: 60.4, speaker: 'danny', text: 'GOAAAL!', cps: 11, hold: .7, energy: 1.4, silentBubble: true },
    { at: 60.4, speaker: 'jenna', text: 'GOAAAL!', cps: 11, hold: .7, energy: 1.4, silentBubble: true },
    { at: 63.2, speaker: 'jester_fester', text: 'Offside! *Again!*', cps: 15, hold: .4, energy: 1.2 },
    { at: 65.0, speaker: 'housam', text: 'WHY???', cps: 10, hold: .8, kind: 'shout', energy: 1.4, group: ['housam', 'alma', 'jenna', 'danny'] },
    { at: 65.0, speaker: 'alma', text: 'WHY???', cps: 10, hold: .8, energy: 1.4, silentBubble: true },
    { at: 65.0, speaker: 'jenna', text: 'WHY???', cps: 10, hold: .8, energy: 1.4, silentBubble: true },
    { at: 65.0, speaker: 'danny', text: 'WHY???', cps: 10, hold: .8, energy: 1.4, silentBubble: true },
    // the explanation
    { at: 67.6, speaker: 'jester_fester', text: 'Allow me to explain... *Safadi-style*!', cps: 17, hold: .3, energy: 1.1 },
    { at: 71.0, speaker: 'jester_fester', text: 'When the ball is passed *forward* to you...', cps: 18, hold: .2 },
    { at: 73.8, speaker: 'jester_fester', text: '...you need *TWO* opponents between you and their goal line.', cps: 19, hold: .4 },
    { at: 77.6, speaker: 'jester_fester', text: 'One: the *goalkeeper*.', cps: 16, hold: .4 },
    { at: 79.8, speaker: 'jester_fester', text: 'Two: usually a *defender*. But their only other player is...', cps: 19, hold: .2 },
    { at: 83.6, speaker: 'jester_fester', text: '...way over *there*! You only had *ONE*. Offside!', cps: 19, hold: .4, energy: 1.1 },
    { at: 87.2, speaker: 'housam', text: 'Ohhhh!', cps: 10, hold: .4, group: ['housam', 'alma', 'jenna', 'danny'] },
    { at: 87.2, speaker: 'alma', text: 'Ohhhh!', cps: 10, hold: .4, silentBubble: true },
    { at: 87.2, speaker: 'jenna', text: 'Ohhhh!', cps: 10, hold: .4, silentBubble: true },
    { at: 87.2, speaker: 'danny', text: 'Ohhhh!', cps: 10, hold: .4, silentBubble: true },
    { at: 88.4, speaker: 'jester_fester', text: "And *that's* why we call it the off—", cps: 20, hold: .05, energy: 1.1 },
    { at: 90.6, speaker: 'safadi', text: 'Ahem. Explanation is *MY* business, Jester.', cps: 17, hold: .5 },
    { at: 94.0, speaker: 'jester_fester', text: 'Anyway...', cps: 10, hold: .3, energy: .85 },
    { at: 95.4, speaker: 'jester_fester', text: "...it's *half-time*!", cps: 15, hold: .4, energy: 1.2 },
  ],
  music: {
    prompt: 'A bouncy, sneaky match score: tiptoeing pizzicato for the twins\' huddle, a driving pulse for play that stops dead on every referee whistle, a big brassy "GOAL" sting cut off mid-note twice, a heroic swell for Alma\'s save, a professorial little "lesson" theme for Fester\'s explanation, and a final whistle into a "to be continued" hit.',
    bpm: 120, tonic: 62, motif: [0, 2, 4, 7, 9, 7, 4, 2], chords: [0, 4, 5, 3],
    sections: [
      { at: 0, energy: .45 }, { at: 4.0, energy: .2 }, { at: 14.0, energy: .45 }, { at: 17.6, energy: .7 }, { at: 25.0, energy: .5 },
      { at: 27.0, energy: .95 }, { at: 31.2, energy: 0 }, { at: 32.0, energy: .2 }, { at: 41.0, energy: .7 }, { at: 47.8, energy: .95 },
      { at: 49.0, energy: .3 }, { at: 53.5, energy: .75 }, { at: 59.2, energy: 1 }, { at: 62.6, energy: 0 }, { at: 65.0, energy: .4 },
      { at: 67.6, energy: .25 }, { at: 89.8, energy: .1 }, { at: 94.0, energy: .3 }, { at: 97.0, energy: .7 }, { at: 99.6, energy: .5 },
      { at: 104.0, energy: 0 },
    ],
    cues: [
      { at: 5.0, type: 'pop' }, { at: 17.6, type: 'whistle' }, { at: 21.8, type: 'whoosh' }, { at: 22.2, type: 'whoosh' }, { at: 26.9, type: 'bonk' },
      { at: 27.6, type: 'ding' }, { at: 31.2, type: 'whistle' }, { at: 34.4, type: 'bonk' }, { at: 36.2, type: 'plip' }, { at: 41.0, type: 'bonk' },
      { at: 44.5, type: 'whoosh' }, { at: 47.3, type: 'bonk' }, { at: 47.85, type: 'bonk' }, { at: 47.9, type: 'ding' },
      { at: 54.4, type: 'whoosh' }, { at: 55.9, type: 'pop' }, { at: 57.6, type: 'pop' }, { at: 58.6, type: 'plip' }, { at: 59.25, type: 'bonk' },
      { at: 59.7, type: 'whoosh' }, { at: 59.9, type: 'ding' }, { at: 62.6, type: 'whistle' }, { at: 70.0, type: 'pop' },
      { at: 77.8, type: 'plip' }, { at: 80.0, type: 'plip' }, { at: 85.6, type: 'ding' }, { at: 89.9, type: 'whoosh' }, { at: 90.1, type: 'pop' },
      { at: 97.0, type: 'whistle' }, { at: 99.6, type: 'ding' },
    ],
  },
});
