// Scene 06: a patient, visual introduction to the question behind the Riemann hypothesis.
asset({
  title: 'The prime-number puzzle',
  logline: 'Outside DCES, Professor Safadi helps Housam and Alma understand what the Riemann hypothesis asks, one picture at a time.',
  files: ['scene.js'],
  docs: 'README.md',
  cast: ['safadi', 'housam', 'alma'],
  locations: ['dces'],
  dialogue: [
    { at: 0.8, speaker: 'housam', text: 'Professor, what is the *Riemann hypothesis*?', cps: 22, hold: 1.1 },
    { at: 4.5, speaker: 'safadi', text: "Let's start where you are: *prime numbers*.", cps: 21, hold: 1.0 },
    { at: 8.5, speaker: 'alma', text: 'Two, three, five, seven... they skip around!', cps: 23, hold: 1.0 },
    { at: 12.2, speaker: 'safadi', text: 'Exactly. Their rhythm is uneven.', cps: 21, hold: 1.0 },
    { at: 15.7, speaker: 'housam', text: 'Like a soccer team changing its passes?', cps: 23, hold: 1.0 },
    { at: 19.5, speaker: 'safadi', text: 'Yes! But can we predict the *overall pattern*?', cps: 21, hold: 1.0 },
    { at: 23.8, speaker: 'alma', text: 'We could count them as we go!', cps: 23, hold: 1.0 },
    { at: 27.0, speaker: 'safadi', text: 'The count climbs in steps. A smooth curve *estimates* it.', cps: 22, hold: 1.1 },
    { at: 32.0, speaker: 'housam', text: 'The steps wobble around the curve.', cps: 23, hold: 1.0 },
    { at: 35.7, speaker: 'safadi', text: 'Riemann found a way to study that wobble.', cps: 22, hold: 1.0 },
    { at: 39.6, speaker: 'safadi', text: 'He used a mathematical machine called *zeta*.', cps: 22, hold: 1.0 },
    { at: 43.6, speaker: 'housam', text: "A machine? We're still in school!", cps: 23, hold: 1.0, energy: .9 },
    { at: 47.0, speaker: 'alma', text: 'My brain just did a backflip.', cps: 23, hold: 1.0, energy: .85 },
    { at: 50.6, speaker: 'safadi', text: "That's okay. Let's draw a map, one step at a time.", cps: 22, hold: 1.0 },
    { at: 55.0, speaker: 'safadi', text: 'Some inputs make zeta equal *zero*.', cps: 22, hold: 1.0 },
    { at: 58.6, speaker: 'safadi', text: 'The interesting zeros live in this strip.', cps: 22, hold: 1.0 },
    { at: 62.5, speaker: 'housam', text: 'Between zero and one across the map?', cps: 23, hold: 1.0 },
    { at: 66.0, speaker: 'safadi', text: 'The hypothesis says *every* one sits on the center line.', cps: 22, hold: 1.0 },
    { at: 71.2, speaker: 'alma', text: 'So the line is *one-half*!', cps: 23, hold: 1.0, energy: 1.15 },
    { at: 74.5, speaker: 'safadi', text: 'Yes. Real part one-half, however high the point.', cps: 22, hold: 1.0 },
    { at: 79.0, speaker: 'housam', text: 'And those points help describe the prime-counting wobble?', cps: 23, hold: 1.0 },
    { at: 83.6, speaker: 'safadi', text: "Yes. We still can't prove they *all* line up.", cps: 22, hold: 1.0 },
    { at: 88.0, speaker: 'housam', text: 'So we understand the *question*...', cps: 23, hold: 1.0 },
    { at: 91.1, speaker: 'alma', text: "...without claiming we've solved it!", cps: 23, hold: 1.0 },
    { at: 94.6, speaker: 'safadi', text: "Exactly. That's real mathematical thinking.", cps: 22, hold: 1.0 },
    { at: 98.6, speaker: 'housam', text: 'I can see the pattern now!', cps: 23, hold: 1.0, energy: 1.18 },
    { at: 101.5, speaker: 'alma', text: 'And I can dance to the prime beat!', cps: 23, hold: 1.0, energy: 1.25 },
    { at: 105.3, speaker: 'safadi', text: 'Keep asking good questions!', cps: 22, hold: 1.5, energy: 1.12 },
  ],
  music: {
    prompt: 'Warm, curious classroom music with soft bass, gently ticking notes and bright bells. Ease back when the children feel lost; swell as the center-line idea clicks, then celebrate lightly. Instrumental under cartoon dialogue.',
    bpm: 96, tonic: 62, motif: [0, 2, 4, 2, 5, 4, 1, 3], chords: [0, 3, 4, 0],
    sections: [
      { at: 0, energy: .3 }, { at: 10, energy: .43 }, { at: 25, energy: .5 },
      { at: 42, energy: .2 }, { at: 50, energy: .3 }, { at: 65, energy: .52 },
      { at: 83, energy: .38 }, { at: 94, energy: .6 }, { at: 100, energy: .78 }, { at: 108, energy: .2 },
    ],
    cues: [
      { at: 8.8, type: 'plip' }, { at: 23.8, type: 'pop' }, { at: 39.8, type: 'ding' },
      { at: 55.3, type: 'plip' }, { at: 66.5, type: 'ding' }, { at: 71.5, type: 'plip' },
      { at: 98.8, type: 'pop' }, { at: 101.8, type: 'ding' },
    ],
  },
});
